2020-09-16 10:51:49,866 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:02:06,302 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:02:24,820 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:05:03,138 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:08:06,283 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:09:19,165 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:09:44,118 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:14:37,180 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:22:33,121 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:22:35,927 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:22:38,543 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:27:52,644 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:28:04,586 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:31:23,879 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:35:37,185 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:36:19,987 ERROR: Exception on /words_errors [POST] [in c:\users\1\web_app1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\web_app1\app\routes.py", line 190, in get_words_errors
    words = reuqest.form['error_words']
NameError: name 'reuqest' is not defined
2020-09-16 11:36:50,904 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:37:05,326 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:44:18,650 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:45:12,473 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:45:32,534 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-16 11:45:42,817 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:16:47,132 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:19:05,344 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:21:39,086 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:21:43,107 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:24:01,353 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:28:33,224 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:35:57,869 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:43:45,935 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 17:44:37,385 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 18:46:52,956 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 18:48:03,762 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 18:49:22,087 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 18:49:36,830 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 18:52:11,651 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-20 18:54:25,943 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-21 20:20:12,457 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-21 20:20:25,041 ERROR: Exception on /yes_not [GET] [in c:\users\1\web_app1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\web_app1\app\routes.py", line 122, in yes_not
    return render_template('game_yes_not.html', title = 'True or False Game')
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: game_yes_not.html
2020-09-21 20:20:47,173 INFO: Lang startup [in C:\Users\1\web_app1\app\__init__.py:33]
2020-09-21 20:20:50,606 ERROR: Exception on /yes_not [GET] [in c:\users\1\web_app1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\web_app1\app\routes.py", line 122, in yes_not
    return render_template('game_yes_not.html', title = 'True or False Game')
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\1\web_app1\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\1\web_app1\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: game_yes_not.html
